const express = require('express');
const path = require('path')
const app = express();
const isBanned= require('../middleware/isBanned')
const isAuthenticated = require('../middleware/auth')
const userController = require('../controllers/userController')
const cartController = require('../controllers/cartController')
const whishlistController = require('../controllers/whishlistController')
const productController = require('../controllers/productController')
const addressController = require('../controllers/addressController')
const couponController = require('../controllers/couponController')
const orderController = require('../controllers/orderController')
app.set('views', path.join(__dirname, '../views/users'));
app.use((req,res,next)=>{
    res.setHeader('Cache-Control','no-cache , no-store')
    next()
  })
app.get('/',userController.loadHome)
app.get('/login',isAuthenticated,isBanned,userController.loadLogin)
app.get('/register',userController.loadRegister)
app.get('/logout',userController.logoutUser)
app.get('/forgetPass',userController.loadForget)
app.get('/shop',productController.loadShop)
app.get('/cart',isAuthenticated,isBanned,cartController.loadCart)
app.get('/wishlist',isAuthenticated,isBanned,whishlistController.loadWishlist)
app.get('/showProduct',isAuthenticated,productController.showProduct)
app.get('/profile',isAuthenticated,isBanned,userController.loadProfile)
app.get('/changePassword',isAuthenticated,isBanned,userController.changePass)
app.get('/checkout',isAuthenticated,isBanned,productController.loadCheckout)
app.get('/viewProducts',isAuthenticated,isBanned,productController.viewProducts)
app.get('/removeCoupon',isAuthenticated,isBanned,couponController.rmCoupon)
app.get('/addAddress',isAuthenticated,isBanned,addressController.loadAddAddress)
app.get('/editAddress',isAuthenticated,isBanned,addressController.loadEditAddress)
app.get('/viewAddress',isAuthenticated,isBanned,addressController.loadViewAddress)
app.get('/deleteAddress',isAuthenticated,isBanned,addressController.deleteAddress)
app.get('/cancelOrder',isAuthenticated,isBanned,orderController.cancellOrder)
app.get('/orderSuccess',isAuthenticated,isBanned,orderController.orderSuccess)
app.get('/orders',isAuthenticated,isBanned,orderController.loadMyOrders)
app.get('/changePass',isAuthenticated,userController.loadChangepass)

app.post('/login',userController.verifyUser)
app.post('/verifyOtp',userController.verifyOtp)
app.post('/register',userController.saveuser)
app.post('/checkUsername',userController.checkUsername)
app.post('/forgetPass',userController.sendForget)
app.post('/editAddress',addressController.resaveAddress)
app.post('/placeOrder',orderController.placeOrder)
app.post('/changePassword',userController.saveChangePassword)
app.post('/profile',userController.saveUsername)
app.post('/verifyPayment',orderController.verifyPayment)
app.post('/addAddress',addressController.saveAddress)
app.post('/getBanner',userController.getBanner)
app.post('/checkout',couponController.checkCoupon)
app.post('/changePass',userController.savePassword)
app.post('/shop',productController.searchProduct)
app.post('/addToCart',cartController.addToCart)
app.post('/removeFromCart',cartController.removeFromCart)
app.post('/addToWishlist',whishlistController.addToWhishlist)
app.post('/wishlist',whishlistController.searchProduct)
app.post('/removeWishlist',whishlistController.removeWishlist)

module.exports = app;
